apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service
spec:
  type: NodePort
  selector:
    app: flask-hello
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
